theme: jekyll-theme-minimal
title: Griffith University Library's online data training
description: This is where you will find all our self-paced online learning materials for wrangling your data.
logo: /assets/LibraryLogo2020.png


