theme: jekyll-theme-dinky
title: Online data training
description: This is where you will find Griffith University Library's self-paced online learning materials for wrangling your data.
logo: /assets/LibraryLogo2020.png


