theme: jekyll-theme-minimal
title: Welcome to Griffith University Library's online data training homepage.
description: This is where you will find all our self-paced online learning materials for wrangling your data.
Logo: /assets/Library Logo 2020.png

